BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `users` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	`Password`	TEXT NOT NULL,
	PRIMARY KEY(`ID`)
);
INSERT INTO `users` (ID,Name,Password) VALUES (1,'dms','1234');
COMMIT;
